import streamlit as st
import requests
from PIL import Image
from io import BytesIO

# Set your Fal.ai API key
API_KEY = "0f2711f9-87e3-4d64-aa8b-a6b31aaffeb0:b0ab8c100de1d5ed26b0a0ff7df1512e"

# API Endpoint for FLUX.1 model
FAL_API_URL = "https://fal.ai/api/v1/models/fal-ai/flux/dev/generate"

# Streamlit UI
st.title("🖼️ AI Image Generator using Fal.ai")
st.write("Enter a text prompt and generate an AI image!")

prompt = st.text_input("Enter your prompt:", "A futuristic cityscape at sunset")

if st.button("Generate Image"):
    st.write("⏳ Generating... Please wait.")

    # API request
    headers = {"Authorization": f"Bearer {API_KEY}"}
    data = {"prompt": prompt}
    response = requests.post(FAL_API_URL, json=data, headers=headers)

    if response.status_code == 200:
        image_url = response.json().get("image_url")
        st.image(image_url, caption="Generated by Fal.ai")
    else:
        st.error(f"Error: {response.status_code} - {response.text}")

