import streamlit as st
import fal_client
import time

# Set your Fal.ai API key
API_KEY = "0f2711f9-87e3-4d64-aa8b-a6b31aaffeb0:b0ab8c100de1d5ed26b0a0ff7df1512e"

# Authenticate with Fal.ai
fal_client.auth(API_KEY)

# Streamlit UI
st.title("🖼️ AI Image Generator using Fal.ai")
st.write("Enter a text prompt and generate an AI image!")

# User input
prompt = st.text_input("Enter your prompt:", "A futuristic cityscape at sunset")

# Submit request to Fal.ai
if st.button("Generate Image"):
    st.write("⏳ Submitting request...")

    handler = fal_client.submit(
        "fal-ai/flux/dev",
        arguments={"prompt": prompt, "num_images": 1}
    )

    request_id = handler.request_id
    st.session_state["request_id"] = request_id  # Store request ID
    st.write(f"✅ Request submitted! Request ID: {request_id}")

# Check if request_id exists and add a "Check Result" button
if "request_id" in st.session_state:
    if st.button("Check Result"):
        st.write("🔄 Checking result...")
        
        result = fal_client.get_result(st.session_state["request_id"])

        if "image_url" in result:
            st.image(result["image_url"], caption="Generated by Fal.ai")
        else:
            st.error("Image not ready yet. Try again later.")
