import streamlit as st
import requests

# Set your Fal.ai API key
API_KEY = "0f2711f9-87e3-4d64-aa8b-a6b31aaffeb0:b0ab8c100de1d5ed26b0a0ff7df1512e"

# Correct API endpoint
FAL_API_URL = "https://fal.ai/api/v1/subscribe"

# Streamlit UI
st.title("🖼️ AI Image Generator using Fal.ai")
st.write("Enter a text prompt and generate an AI image!")

prompt = st.text_input("Enter your prompt:", "A futuristic cityscape at sunset")

if st.button("Generate Image"):
    st.write("⏳ Generating... Please wait.")

    # API request
    headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}
    data = {
        "model_id": "fal-ai/flux/dev",  # This is the correct way to specify the model
        "input": {"prompt": prompt}
    }

    response = requests.post(FAL_API_URL, json=data, headers=headers)

    st.write(f"API Response: {response.status_code}, {response.text}")  # Debugging info

    if response.status_code == 200:
        result = response.json()
        image_url = result.get("image_url")  # Adjust according to API response
        if image_url:
            st.image(image_url, caption="Generated by Fal.ai")
        else:
            st.error("No image URL returned by API.")
    else:
        st.error(f"Error {response.status_code}: {response.text}")
